[versions]
gherkin = "28.0.0"
json-rpc2 = "2.1.1"
okhttp = "4.12.0"

[libraries]
gherkin = { module = "io.cucumber:gherkin", version.ref="gherkin" }
json-rpc2 = { module = "com.thetransactioncompany:jsonrpc2-base", version.ref="json-rpc2" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref="okhttp" }